### ISSUE TITLE
Repeating iPhone Alerts for Reply to Post

### ISSUE THREAD

**Issue by shangles** [cjhodge/EveningReading#7]
I received a reply to one of my posts in [this thread](https://www.shacknews.com/chatty?id=42378554#item_42378554) tonight ([link to my reply](https://www.shacknews.com/chatty?id=42379013#item_42379013)) and my phone will not stop popping an iOS notification for this one reply.  I've rebooted my phone.  I've logged out of the app and back in again.  The only thing to stop the constant repeating alert is to disable notifications for Evening Reading in my iOS settings

iPhone 11 Pro
iOS 17.4.1
App version 2.04

**Comment by shangles** [comment]
Sikander's reply to my thread was nuked but I'm still getting notifications for it on my phone every 5-10 seconds.

**Comment by shangles** [comment]
His link was to an http://web.archive.org/web link

**Comment by shangles** [comment]
Trying to delete the app and reinstall now.

**Comment by shangles** [comment]
I uninstalled the app, rebooted, reinstalled, still getting the notification

**Comment by shangles** [comment]
I’m getting duplicate alerts for other replies to me in this thread as well

**Comment by cjhodge** [comment]
Let me know if this is still happening.  It's a server issue.

**Comment by shangles** [comment]
All good now.  Thanks!
